[package]
name = "beast_common"
version = "1.0.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ron = "0.9"
time = { version = "0.3", features = ["serde", "formatting", "parsing", "local-offset"] }