[package]
name = "highscore_parser"
version = "1.0.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ron = "0.9"
time = { version = "0.3", features = ["serde", "formatting", "parsing"] }